// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class Bookmark
{
    public int BookmarkId { get; set; }

    public int UserIdHuyDd { get; set; }

    public int PaperIdBaoTg { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual PapersBaoTg PaperIdBaoTgNavigation { get; set; }

    public virtual UsersHuyDd UserIdHuyDdNavigation { get; set; }
}