// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class ImportedFile
{
    public int ImportedFileId { get; set; }

    public string FileName { get; set; }

    public string FileUrl { get; set; }

    public string FileType { get; set; }

    public int? UploadedByHuyDd { get; set; }

    public int TotalRows { get; set; }

    public int ImportedRows { get; set; }

    public int FailedRows { get; set; }

    public string Status { get; set; }

    public DateTime UploadedAt { get; set; }

    public virtual UsersHuyDd UploadedByHuyDdNavigation { get; set; }
}