// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class KeywordsLuanNtk
{
    public int KeywordIdLuanNtk { get; set; }

    public string KeywordName { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<TrendRecord> TrendRecords { get; set; } = new List<TrendRecord>();

    public virtual ICollection<UserFollowKeyword> UserFollowKeywords { get; set; } = new List<UserFollowKeyword>();

    public virtual ICollection<PapersBaoTg> PaperIdBaoTgs { get; set; } = new List<PapersBaoTg>();

    public virtual ICollection<TopicsLuanNtk> Topics { get; set; } = new List<TopicsLuanNtk>();
}