// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class Notification
{
    public int NotificationId { get; set; }

    public int UserIdHuyDd { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public string NotificationType { get; set; }

    public int? RelatedPaperIdBaoTg { get; set; }

    public int? RelatedTopicId { get; set; }

    public int? RelatedKeywordId { get; set; }

    public bool IsRead { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual KeywordsLuanNtk RelatedKeyword { get; set; }

    public virtual PapersBaoTg RelatedPaperIdBaoTgNavigation { get; set; }

    public virtual TopicsLuanNtk RelatedTopic { get; set; }

    public virtual UsersHuyDd UserIdHuyDdNavigation { get; set; }
}