// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class PapersBaoTg
{
    public int PaperIdBaoTg { get; set; }

    public string Title { get; set; }

    public string Abstract { get; set; }

    public string Doi { get; set; }

    public int? JournalIdMinhPv { get; set; }

    public DateOnly? PublicationDate { get; set; }

    public int? PublicationYear { get; set; }

    public string Volume { get; set; }

    public string Issue { get; set; }

    public string Pages { get; set; }

    public string PaperUrl { get; set; }

    public string PdfUrl { get; set; }

    public string SourceName { get; set; }

    public bool IsOpenAccess { get; set; }

    public int? CreatedByHuyDd { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Bookmark> Bookmarks { get; set; } = new List<Bookmark>();

    public virtual ICollection<CitationHistory> CitationHistories { get; set; } = new List<CitationHistory>();

    public virtual UsersHuyDd CreatedByHuyDdNavigation { get; set; }

    public virtual JournalsMinhPv JournalIdMinhPvNavigation { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<PaperAuthorsBaoTg> PaperAuthorsBaoTgs { get; set; } = new List<PaperAuthorsBaoTg>();

    public virtual PaperMetric PaperMetric { get; set; }

    public virtual ICollection<KeywordsLuanNtk> Keywords { get; set; } = new List<KeywordsLuanNtk>();
}