// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class Publisher
{
    public int PublisherId { get; set; }

    public string PublisherName { get; set; }

    public string Country { get; set; }

    public string WebsiteUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<JournalsMinhPv> JournalsMinhPvs { get; set; } = new List<JournalsMinhPv>();
}