// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class Report
{
    public int ReportId { get; set; }

    public int UserIdHuyDd { get; set; }

    public string ReportName { get; set; }

    public string ReportType { get; set; }

    public string FilterConfig { get; set; }

    public string FileUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual UsersHuyDd UserIdHuyDdNavigation { get; set; }
}