// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class TrendRecord
{
    public int TrendId { get; set; }

    public int? KeywordId { get; set; }

    public int? TopicId { get; set; }

    public int RecordYear { get; set; }

    public int? RecordMonth { get; set; }

    public int PaperCount { get; set; }

    public int CitationCount { get; set; }

    public decimal? GrowthRate { get; set; }

    public decimal? TrendScore { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual KeywordsLuanNtk Keyword { get; set; }

    public virtual TopicsLuanNtk Topic { get; set; }
}