// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class CategoriesMinhPvConfiguration : IEntityTypeConfiguration<CategoriesMinhPv>
    {
        public void Configure(EntityTypeBuilder<CategoriesMinhPv> entity)
        {
            entity.HasKey(e => e.CategoryIdMinhPv).HasName("PK__Categori__9E89C984F81CC943");

            entity.ToTable("Categories_MinhPV");

            entity.HasIndex(e => e.CategoryName, "IX_Categories_MinhPV_CategoryName");

            entity.HasIndex(e => e.CategoryName, "UQ__Categori__8517B2E0266C48F5").IsUnique();

            entity.Property(e => e.CategoryIdMinhPv).HasColumnName("CategoryId_MinhPV");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CategoriesMinhPv> entity);
    }
}
