// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class CitationHistoryConfiguration : IEntityTypeConfiguration<CitationHistory>
    {
        public void Configure(EntityTypeBuilder<CitationHistory> entity)
        {
            entity.HasKey(e => e.CitationHistoryId).HasName("PK__Citation__0CC8A27E7B25781B");

            entity.Property(e => e.PaperIdBaoTg).HasColumnName("PaperId_BaoTG");
            entity.Property(e => e.RecordedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.PaperIdBaoTgNavigation).WithMany(p => p.CitationHistories)
                .HasForeignKey(d => d.PaperIdBaoTg)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CitationHistories_Papers_BaoTG");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CitationHistory> entity);
    }
}
