// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class ExternalSourceConfiguration : IEntityTypeConfiguration<ExternalSource>
    {
        public void Configure(EntityTypeBuilder<ExternalSource> entity)
        {
            entity.HasKey(e => e.SourceId).HasName("PK__External__16E0191934A6CF4D");

            entity.HasIndex(e => e.SourceName, "UQ__External__3C28DC17D4198351").IsUnique();

            entity.Property(e => e.BaseUrl).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.SourceName)
                .IsRequired()
                .HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ExternalSource> entity);
    }
}
