// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class ImportedFileConfiguration : IEntityTypeConfiguration<ImportedFile>
    {
        public void Configure(EntityTypeBuilder<ImportedFile> entity)
        {
            entity.HasKey(e => e.ImportedFileId).HasName("PK__Imported__000007A953E71D26");

            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FileType).HasMaxLength(50);
            entity.Property(e => e.FileUrl).HasMaxLength(500);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.UploadedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UploadedByHuyDd).HasColumnName("UploadedBy_HuyDD");

            entity.HasOne(d => d.UploadedByHuyDdNavigation).WithMany(p => p.ImportedFiles)
                .HasForeignKey(d => d.UploadedByHuyDd)
                .HasConstraintName("FK_ImportedFiles_Users_HuyDD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ImportedFile> entity);
    }
}
