// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class JournalsMinhPvConfiguration : IEntityTypeConfiguration<JournalsMinhPv>
    {
        public void Configure(EntityTypeBuilder<JournalsMinhPv> entity)
        {
            entity.HasKey(e => e.JournalIdMinhPv).HasName("PK__Journals__D14C0DC2559E6BFB");

            entity.ToTable("Journals_MinhPV");

            entity.HasIndex(e => e.JournalName, "IX_Journals_MinhPV_JournalName");

            entity.HasIndex(e => e.PublisherId, "IX_Journals_MinhPV_PublisherId");

            entity.Property(e => e.JournalIdMinhPv).HasColumnName("JournalId_MinhPV");
            entity.Property(e => e.Country).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Eissn)
                .HasMaxLength(50)
                .HasColumnName("EISSN");
            entity.Property(e => e.ImpactFactor).HasColumnType("decimal(10, 3)");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Issn)
                .HasMaxLength(50)
                .HasColumnName("ISSN");
            entity.Property(e => e.JournalName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Ranking).HasMaxLength(50);
            entity.Property(e => e.WebsiteUrl).HasMaxLength(500);

            entity.HasOne(d => d.Publisher).WithMany(p => p.JournalsMinhPvs)
                .HasForeignKey(d => d.PublisherId)
                .HasConstraintName("FK_Journals_MinhPV_Publishers");

            entity.HasMany(d => d.CategoryIdMinhPvs).WithMany(p => p.JournalIdMinhPvs)
                .UsingEntity<Dictionary<string, object>>(
                    "JournalCategoriesMinhPv",
                    r => r.HasOne<CategoriesMinhPv>().WithMany()
                        .HasForeignKey("CategoryIdMinhPv")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_JournalCategories_MinhPV_Categories_MinhPV"),
                    l => l.HasOne<JournalsMinhPv>().WithMany()
                        .HasForeignKey("JournalIdMinhPv")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_JournalCategories_MinhPV_Journals_MinhPV"),
                    j =>
                    {
                        j.HasKey("JournalIdMinhPv", "CategoryIdMinhPv");
                        j.ToTable("JournalCategories_MinhPV");
                        j.IndexerProperty<int>("JournalIdMinhPv").HasColumnName("JournalId_MinhPV");
                        j.IndexerProperty<int>("CategoryIdMinhPv").HasColumnName("CategoryId_MinhPV");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<JournalsMinhPv> entity);
    }
}
