// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class KeywordsLuanNtkConfiguration : IEntityTypeConfiguration<KeywordsLuanNtk>
    {
        public void Configure(EntityTypeBuilder<KeywordsLuanNtk> entity)
        {
            entity.HasKey(e => e.KeywordIdLuanNtk).HasName("PK__Keywords__8749800078702951");

            entity.ToTable("Keywords_LuanNTK");

            entity.HasIndex(e => e.KeywordName, "IX_Keywords_KeywordName");

            entity.HasIndex(e => e.KeywordName, "UQ__Keywords__830B48D9D40D0DA5").IsUnique();

            entity.Property(e => e.KeywordIdLuanNtk).HasColumnName("KeywordId_LuanNTK");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.KeywordName)
                .IsRequired()
                .HasMaxLength(150);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KeywordsLuanNtk> entity);
    }
}
