// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class PaperMetricConfiguration : IEntityTypeConfiguration<PaperMetric>
    {
        public void Configure(EntityTypeBuilder<PaperMetric> entity)
        {
            entity.HasKey(e => e.PaperMetricId).HasName("PK__PaperMet__52CA8932B7692B65");

            entity.HasIndex(e => e.PaperIdBaoTg, "UQ__PaperMet__14DD944F52254EA4").IsUnique();

            entity.Property(e => e.AltmetricScore).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PaperIdBaoTg).HasColumnName("PaperId_BaoTG");

            entity.HasOne(d => d.PaperIdBaoTgNavigation).WithOne(p => p.PaperMetric)
                .HasForeignKey<PaperMetric>(d => d.PaperIdBaoTg)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaperMetrics_Papers_BaoTG");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PaperMetric> entity);
    }
}
