// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class PaperAuthorsBaoTgConfiguration : IEntityTypeConfiguration<PaperAuthorsBaoTg>
    {
        public void Configure(EntityTypeBuilder<PaperAuthorsBaoTg> entity)
        {
            entity.HasKey(e => new { e.PaperIdBaoTg, e.AuthorIdBaoTg });

            entity.ToTable("PaperAuthors_BaoTG");

            entity.Property(e => e.PaperIdBaoTg).HasColumnName("PaperId_BaoTG");
            entity.Property(e => e.AuthorIdBaoTg).HasColumnName("AuthorId_BaoTG");

            entity.HasOne(d => d.AuthorIdBaoTgNavigation).WithMany(p => p.PaperAuthorsBaoTgs)
                .HasForeignKey(d => d.AuthorIdBaoTg)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaperAuthors_BaoTG_Authors_BaoTG");

            entity.HasOne(d => d.PaperIdBaoTgNavigation).WithMany(p => p.PaperAuthorsBaoTgs)
                .HasForeignKey(d => d.PaperIdBaoTg)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaperAuthors_BaoTG_Papers_BaoTG");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PaperAuthorsBaoTg> entity);
    }
}
