// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class PapersBaoTgConfiguration : IEntityTypeConfiguration<PapersBaoTg>
    {
        public void Configure(EntityTypeBuilder<PapersBaoTg> entity)
        {
            entity.HasKey(e => e.PaperIdBaoTg).HasName("PK__Papers_B__14DD944E23471288");

            entity.ToTable("Papers_BaoTG");

            entity.HasIndex(e => e.CreatedByHuyDd, "IX_Papers_BaoTG_CreatedBy_HuyDD");

            entity.HasIndex(e => e.JournalIdMinhPv, "IX_Papers_BaoTG_JournalId_MinhPV");

            entity.HasIndex(e => e.PublicationYear, "IX_Papers_BaoTG_PublicationYear");

            entity.HasIndex(e => e.Title, "IX_Papers_BaoTG_Title");

            entity.HasIndex(e => e.Doi, "UQ__Papers_B__C03580FC5B1EC81E").IsUnique();

            entity.Property(e => e.PaperIdBaoTg).HasColumnName("PaperId_BaoTG");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedByHuyDd).HasColumnName("CreatedBy_HuyDD");
            entity.Property(e => e.Doi)
                .HasMaxLength(255)
                .HasColumnName("DOI");
            entity.Property(e => e.Issue).HasMaxLength(50);
            entity.Property(e => e.JournalIdMinhPv).HasColumnName("JournalId_MinhPV");
            entity.Property(e => e.Pages).HasMaxLength(50);
            entity.Property(e => e.PaperUrl).HasMaxLength(500);
            entity.Property(e => e.PdfUrl).HasMaxLength(500);
            entity.Property(e => e.SourceName).HasMaxLength(100);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.Volume).HasMaxLength(50);

            entity.HasOne(d => d.CreatedByHuyDdNavigation).WithMany(p => p.PapersBaoTgs)
                .HasForeignKey(d => d.CreatedByHuyDd)
                .HasConstraintName("FK_Papers_BaoTG_Users_HuyDD");

            entity.HasOne(d => d.JournalIdMinhPvNavigation).WithMany(p => p.PapersBaoTgs)
                .HasForeignKey(d => d.JournalIdMinhPv)
                .HasConstraintName("FK_Papers_BaoTG_Journals_MinhPV");

            entity.HasMany(d => d.Keywords).WithMany(p => p.PaperIdBaoTgs)
                .UsingEntity<Dictionary<string, object>>(
                    "PaperKeywordsLuanNtk",
                    r => r.HasOne<KeywordsLuanNtk>().WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PaperKeywords_Keywords"),
                    l => l.HasOne<PapersBaoTg>().WithMany()
                        .HasForeignKey("PaperIdBaoTg")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PaperKeywords_Papers_BaoTG"),
                    j =>
                    {
                        j.HasKey("PaperIdBaoTg", "KeywordId").HasName("PK_PaperKeywords");
                        j.ToTable("PaperKeywords_LuanNTK");
                        j.IndexerProperty<int>("PaperIdBaoTg").HasColumnName("PaperId_BaoTG");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PapersBaoTg> entity);
    }
}
