// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class TopicsLuanNtkConfiguration : IEntityTypeConfiguration<TopicsLuanNtk>
    {
        public void Configure(EntityTypeBuilder<TopicsLuanNtk> entity)
        {
            entity.HasKey(e => e.TopicIdLuanNtk).HasName("PK__Topics_L__74FE05E481843A38");

            entity.ToTable("Topics_LuanNTK");

            entity.HasIndex(e => e.TopicName, "IX_Topics_TopicName");

            entity.HasIndex(e => e.TopicName, "UQ__Topics_L__6C795E8C08E16A12").IsUnique();

            entity.Property(e => e.TopicIdLuanNtk).HasColumnName("TopicId_LuanNTK");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.TopicName)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasMany(d => d.Keywords).WithMany(p => p.Topics)
                .UsingEntity<Dictionary<string, object>>(
                    "TopicKeywordsLuanNtk",
                    r => r.HasOne<KeywordsLuanNtk>().WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TopicKeywords_Keywords"),
                    l => l.HasOne<TopicsLuanNtk>().WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TopicKeywords_Topics"),
                    j =>
                    {
                        j.HasKey("TopicId", "KeywordId").HasName("PK_TopicKeywords");
                        j.ToTable("TopicKeywords_LuanNTK");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TopicsLuanNtk> entity);
    }
}
