// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class AuthorsBaoTgConfiguration : IEntityTypeConfiguration<AuthorsBaoTg>
    {
        public void Configure(EntityTypeBuilder<AuthorsBaoTg> entity)
        {
            entity.HasKey(e => e.AuthorIdBaoTg).HasName("PK__Authors___D7ACACF8F7FC8A8B");

            entity.ToTable("Authors_BaoTG");

            entity.HasIndex(e => e.FullName, "IX_Authors_BaoTG_FullName");

            entity.Property(e => e.AuthorIdBaoTg).HasColumnName("AuthorId_BaoTG");
            entity.Property(e => e.Affiliation).HasMaxLength(255);
            entity.Property(e => e.Country).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.GoogleScholarUrl).HasMaxLength(500);
            entity.Property(e => e.Orcid)
                .HasMaxLength(100)
                .HasColumnName("ORCID");
            entity.Property(e => e.ScopusId).HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AuthorsBaoTg> entity);
    }
}
