// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class AuthorMetricConfiguration : IEntityTypeConfiguration<AuthorMetric>
    {
        public void Configure(EntityTypeBuilder<AuthorMetric> entity)
        {
            entity.HasKey(e => e.AuthorMetricId).HasName("PK__AuthorMe__97987E4D48FF1414");

            entity.HasIndex(e => e.AuthorIdBaoTg, "UQ__AuthorMe__D7ACACF9D145FB7C").IsUnique();

            entity.Property(e => e.AuthorIdBaoTg).HasColumnName("AuthorId_BaoTG");
            entity.Property(e => e.Hindex).HasColumnName("HIndex");
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.AuthorIdBaoTgNavigation).WithOne(p => p.AuthorMetric)
                .HasForeignKey<AuthorMetric>(d => d.AuthorIdBaoTg)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AuthorMetrics_Authors_BaoTG");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AuthorMetric> entity);
    }
}
