// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class BookmarkConfiguration : IEntityTypeConfiguration<Bookmark>
    {
        public void Configure(EntityTypeBuilder<Bookmark> entity)
        {
            entity.HasKey(e => e.BookmarkId).HasName("PK__Bookmark__541A3B71A629579C");

            entity.HasIndex(e => e.UserIdHuyDd, "IX_Bookmarks_UserId_HuyDD");

            entity.HasIndex(e => new { e.UserIdHuyDd, e.PaperIdBaoTg }, "UQ_Bookmarks_User_Paper").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Note).HasMaxLength(500);
            entity.Property(e => e.PaperIdBaoTg).HasColumnName("PaperId_BaoTG");
            entity.Property(e => e.UserIdHuyDd).HasColumnName("UserId_HuyDD");

            entity.HasOne(d => d.PaperIdBaoTgNavigation).WithMany(p => p.Bookmarks)
                .HasForeignKey(d => d.PaperIdBaoTg)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookmarks_Papers_BaoTG");

            entity.HasOne(d => d.UserIdHuyDdNavigation).WithMany(p => p.Bookmarks)
                .HasForeignKey(d => d.UserIdHuyDd)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookmarks_Users_HuyDD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Bookmark> entity);
    }
}
