// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class NotificationConfiguration : IEntityTypeConfiguration<Notification>
    {
        public void Configure(EntityTypeBuilder<Notification> entity)
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E1226F97807");

            entity.HasIndex(e => new { e.UserIdHuyDd, e.IsRead }, "IX_Notifications_UserId_HuyDD_IsRead");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Message).HasMaxLength(1000);
            entity.Property(e => e.NotificationType).HasMaxLength(50);
            entity.Property(e => e.RelatedPaperIdBaoTg).HasColumnName("RelatedPaperId_BaoTG");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UserIdHuyDd).HasColumnName("UserId_HuyDD");

            entity.HasOne(d => d.RelatedKeyword).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.RelatedKeywordId)
                .HasConstraintName("FK_Notifications_Keywords");

            entity.HasOne(d => d.RelatedPaperIdBaoTgNavigation).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.RelatedPaperIdBaoTg)
                .HasConstraintName("FK_Notifications_Papers_BaoTG");

            entity.HasOne(d => d.RelatedTopic).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.RelatedTopicId)
                .HasConstraintName("FK_Notifications_Topics");

            entity.HasOne(d => d.UserIdHuyDdNavigation).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserIdHuyDd)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notifications_Users_HuyDD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Notification> entity);
    }
}
