// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class ReportConfiguration : IEntityTypeConfiguration<Report>
    {
        public void Configure(EntityTypeBuilder<Report> entity)
        {
            entity.HasKey(e => e.ReportId).HasName("PK__Reports__D5BD4805ADB7DEE0");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FileUrl).HasMaxLength(500);
            entity.Property(e => e.ReportName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ReportType).HasMaxLength(100);
            entity.Property(e => e.UserIdHuyDd).HasColumnName("UserId_HuyDD");

            entity.HasOne(d => d.UserIdHuyDdNavigation).WithMany(p => p.Reports)
                .HasForeignKey(d => d.UserIdHuyDd)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reports_Users_HuyDD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Report> entity);
    }
}
