// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class RolesHuyDdConfiguration : IEntityTypeConfiguration<RolesHuyDd>
    {
        public void Configure(EntityTypeBuilder<RolesHuyDd> entity)
        {
            entity.HasKey(e => e.RoleIdHuyDd).HasName("PK__Roles_Hu__4F00A61300757A4D");

            entity.ToTable("Roles_HuyDD");

            entity.HasIndex(e => e.RoleName, "UQ__Roles_Hu__8A2B61604EEA6DBB").IsUnique();

            entity.Property(e => e.RoleIdHuyDd).HasColumnName("RoleId_HuyDD");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RolesHuyDd> entity);
    }
}
