// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class TrendRecordConfiguration : IEntityTypeConfiguration<TrendRecord>
    {
        public void Configure(EntityTypeBuilder<TrendRecord> entity)
        {
            entity.HasKey(e => e.TrendId).HasName("PK__TrendRec__DACD10F70CD6FA2C");

            entity.HasIndex(e => e.KeywordId, "IX_TrendRecords_KeywordId");

            entity.HasIndex(e => e.TopicId, "IX_TrendRecords_TopicId");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.GrowthRate).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TrendScore).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Keyword).WithMany(p => p.TrendRecords)
                .HasForeignKey(d => d.KeywordId)
                .HasConstraintName("FK_TrendRecords_Keywords");

            entity.HasOne(d => d.Topic).WithMany(p => p.TrendRecords)
                .HasForeignKey(d => d.TopicId)
                .HasConstraintName("FK_TrendRecords_Topics");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TrendRecord> entity);
    }
}
