// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class UserFollowTopicConfiguration : IEntityTypeConfiguration<UserFollowTopic>
    {
        public void Configure(EntityTypeBuilder<UserFollowTopic> entity)
        {
            entity.HasKey(e => new { e.UserIdHuyDd, e.TopicId });

            entity.Property(e => e.UserIdHuyDd).HasColumnName("UserId_HuyDD");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Topic).WithMany(p => p.UserFollowTopics)
                .HasForeignKey(d => d.TopicId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserFollowTopics_Topics");

            entity.HasOne(d => d.UserIdHuyDdNavigation).WithMany(p => p.UserFollowTopics)
                .HasForeignKey(d => d.UserIdHuyDd)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserFollowTopics_Users_HuyDD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserFollowTopic> entity);
    }
}
