// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class UserFollowKeywordConfiguration : IEntityTypeConfiguration<UserFollowKeyword>
    {
        public void Configure(EntityTypeBuilder<UserFollowKeyword> entity)
        {
            entity.HasKey(e => new { e.UserIdHuyDd, e.KeywordId });

            entity.Property(e => e.UserIdHuyDd).HasColumnName("UserId_HuyDD");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Keyword).WithMany(p => p.UserFollowKeywords)
                .HasForeignKey(d => d.KeywordId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserFollowKeywords_Keywords");

            entity.HasOne(d => d.UserIdHuyDdNavigation).WithMany(p => p.UserFollowKeywords)
                .HasForeignKey(d => d.UserIdHuyDd)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserFollowKeywords_Users_HuyDD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserFollowKeyword> entity);
    }
}
