// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class UsersHuyDdConfiguration : IEntityTypeConfiguration<UsersHuyDd>
    {
        public void Configure(EntityTypeBuilder<UsersHuyDd> entity)
        {
            entity.HasKey(e => e.UserIdHuyDd).HasName("PK__Users_Hu__835644DCAE4D85F4");

            entity.ToTable("Users_HuyDD");

            entity.HasIndex(e => e.Email, "IX_Users_HuyDD_Email");

            entity.HasIndex(e => e.Email, "UQ__Users_Hu__A9D10534B6034F94").IsUnique();

            entity.Property(e => e.UserIdHuyDd).HasColumnName("UserId_HuyDD");
            entity.Property(e => e.AcademicTitle).HasMaxLength(100);
            entity.Property(e => e.AvatarUrl).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Organization).HasMaxLength(200);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasMany(d => d.RoleIdHuyDds).WithMany(p => p.UserIdHuyDds)
                .UsingEntity<Dictionary<string, object>>(
                    "UserRolesHuyDd",
                    r => r.HasOne<RolesHuyDd>().WithMany()
                        .HasForeignKey("RoleIdHuyDd")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_UserRoles_HuyDD_Roles_HuyDD"),
                    l => l.HasOne<UsersHuyDd>().WithMany()
                        .HasForeignKey("UserIdHuyDd")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_UserRoles_HuyDD_Users_HuyDD"),
                    j =>
                    {
                        j.HasKey("UserIdHuyDd", "RoleIdHuyDd");
                        j.ToTable("UserRoles_HuyDD");
                        j.IndexerProperty<int>("UserIdHuyDd").HasColumnName("UserId_HuyDD");
                        j.IndexerProperty<int>("RoleIdHuyDd").HasColumnName("RoleId_HuyDD");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UsersHuyDd> entity);
    }
}
