// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ScientificJournal.Entities.MinhPV.Models;
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models.Configurations
{
    public partial class UserFollowJournalConfiguration : IEntityTypeConfiguration<UserFollowJournal>
    {
        public void Configure(EntityTypeBuilder<UserFollowJournal> entity)
        {
            entity.HasKey(e => new { e.UserIdHuyDd, e.JournalIdMinhPv });

            entity.Property(e => e.UserIdHuyDd).HasColumnName("UserId_HuyDD");
            entity.Property(e => e.JournalIdMinhPv).HasColumnName("JournalId_MinhPV");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.JournalIdMinhPvNavigation).WithMany(p => p.UserFollowJournals)
                .HasForeignKey(d => d.JournalIdMinhPv)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserFollowJournals_Journals_MinhPV");

            entity.HasOne(d => d.UserIdHuyDdNavigation).WithMany(p => p.UserFollowJournals)
                .HasForeignKey(d => d.UserIdHuyDd)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserFollowJournals_Users_HuyDD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserFollowJournal> entity);
    }
}
