// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class AuditLog
{
    public int AuditLogId { get; set; }

    public int? UserIdHuyDd { get; set; }

    public string Action { get; set; }

    public string TableName { get; set; }

    public int? RecordId { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public string IpAddress { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual UsersHuyDd UserIdHuyDdNavigation { get; set; }
}