// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class AuthorsBaoTg
{
    public int AuthorIdBaoTg { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Affiliation { get; set; }

    public string Country { get; set; }

    public string Orcid { get; set; }

    public string GoogleScholarUrl { get; set; }

    public string ScopusId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AuthorMetric AuthorMetric { get; set; }

    public virtual ICollection<PaperAuthorsBaoTg> PaperAuthorsBaoTgs { get; set; } = new List<PaperAuthorsBaoTg>();
}