// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class AuthorMetric
{
    public int AuthorMetricId { get; set; }

    public int AuthorIdBaoTg { get; set; }

    public int TotalPapers { get; set; }

    public int TotalCitations { get; set; }

    public int Hindex { get; set; }

    public DateTime LastUpdated { get; set; }

    public virtual AuthorsBaoTg AuthorIdBaoTgNavigation { get; set; }
}