// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class CategoriesMinhPv
{
    public int CategoryIdMinhPv { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<JournalsMinhPv> JournalIdMinhPvs { get; set; } = new List<JournalsMinhPv>();
}