// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class CitationHistory
{
    public int CitationHistoryId { get; set; }

    public int PaperIdBaoTg { get; set; }

    public int CitationCount { get; set; }

    public DateTime RecordedAt { get; set; }

    public virtual PapersBaoTg PaperIdBaoTgNavigation { get; set; }
}