// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class ExternalSource
{
    public int SourceId { get; set; }

    public string SourceName { get; set; }

    public string BaseUrl { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<SyncLog> SyncLogs { get; set; } = new List<SyncLog>();
}