// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class JournalsMinhPv
{
    public int JournalIdMinhPv { get; set; }

    public string JournalName { get; set; }

    public string Issn { get; set; }

    public string Eissn { get; set; }

    public int? PublisherId { get; set; }

    public string Country { get; set; }

    public string WebsiteUrl { get; set; }

    public decimal? ImpactFactor { get; set; }

    public string Ranking { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<PapersBaoTg> PapersBaoTgs { get; set; } = new List<PapersBaoTg>();

    public virtual Publisher Publisher { get; set; }

    public virtual ICollection<UserFollowJournal> UserFollowJournals { get; set; } = new List<UserFollowJournal>();

    public virtual ICollection<CategoriesMinhPv> CategoryIdMinhPvs { get; set; } = new List<CategoriesMinhPv>();
}