// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class PaperAuthorsBaoTg
{
    public int PaperIdBaoTg { get; set; }

    public int AuthorIdBaoTg { get; set; }

    public int AuthorOrder { get; set; }

    public bool IsCorrespondingAuthor { get; set; }

    public virtual AuthorsBaoTg AuthorIdBaoTgNavigation { get; set; }

    public virtual PapersBaoTg PaperIdBaoTgNavigation { get; set; }
}