// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class PaperMetric
{
    public int PaperMetricId { get; set; }

    public int PaperIdBaoTg { get; set; }

    public int CitationCount { get; set; }

    public int ViewCount { get; set; }

    public int DownloadCount { get; set; }

    public int BookmarkCount { get; set; }

    public decimal? AltmetricScore { get; set; }

    public DateTime LastUpdated { get; set; }

    public virtual PapersBaoTg PaperIdBaoTgNavigation { get; set; }
}