// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class RolesHuyDd
{
    public int RoleIdHuyDd { get; set; }

    public string RoleName { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<UsersHuyDd> UserIdHuyDds { get; set; } = new List<UsersHuyDd>();
}