// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using ScientificJournal.Entities.MinhPV.Models.Configurations;
using System;
using System.Collections.Generic;
#nullable disable

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class ScientificJournalTrendDBContext : DbContext
{
    public ScientificJournalTrendDBContext()
    {
    }

    public ScientificJournalTrendDBContext(DbContextOptions<ScientificJournalTrendDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<AuthorMetric> AuthorMetrics { get; set; }

    public virtual DbSet<AuthorsBaoTg> AuthorsBaoTgs { get; set; }

    public virtual DbSet<Bookmark> Bookmarks { get; set; }

    public virtual DbSet<CategoriesMinhPv> CategoriesMinhPvs { get; set; }

    public virtual DbSet<CitationHistory> CitationHistories { get; set; }

    public virtual DbSet<ExternalSource> ExternalSources { get; set; }

    public virtual DbSet<ImportedFile> ImportedFiles { get; set; }

    public virtual DbSet<JournalsMinhPv> JournalsMinhPvs { get; set; }

    public virtual DbSet<KeywordsLuanNtk> KeywordsLuanNtks { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<PaperAuthorsBaoTg> PaperAuthorsBaoTgs { get; set; }

    public virtual DbSet<PaperMetric> PaperMetrics { get; set; }

    public virtual DbSet<PapersBaoTg> PapersBaoTgs { get; set; }

    public virtual DbSet<Publisher> Publishers { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<RolesHuyDd> RolesHuyDds { get; set; }

    public virtual DbSet<SyncLog> SyncLogs { get; set; }

    public virtual DbSet<TopicsLuanNtk> TopicsLuanNtks { get; set; }

    public virtual DbSet<TrendRecord> TrendRecords { get; set; }

    public virtual DbSet<UserFollowJournal> UserFollowJournals { get; set; }

    public virtual DbSet<UserFollowKeyword> UserFollowKeywords { get; set; }

    public virtual DbSet<UserFollowTopic> UserFollowTopics { get; set; }

    public virtual DbSet<UsersHuyDd> UsersHuyDds { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer("Data Source=MINH\\SQLEXPRESS;Initial Catalog=ScientificJournalTrendDB;Persist Security Info=True;User ID=sa;Password=12345;Encrypt=True;TrustServerCertificate=True");
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.AuditLogConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AuthorMetricConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AuthorsBaoTgConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BookmarkConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CategoriesMinhPvConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CitationHistoryConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ExternalSourceConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ImportedFileConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.JournalsMinhPvConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.KeywordsLuanNtkConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.NotificationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PaperAuthorsBaoTgConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PaperMetricConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PapersBaoTgConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PublisherConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ReportConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RolesHuyDdConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SyncLogConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TopicsLuanNtkConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TrendRecordConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserFollowJournalConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserFollowKeywordConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserFollowTopicConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsersHuyDdConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
