// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class SyncLog
{
    public int SyncLogId { get; set; }

    public int SourceId { get; set; }

    public string SyncType { get; set; }

    public string Status { get; set; }

    public int TotalRecords { get; set; }

    public int SuccessRecords { get; set; }

    public int FailedRecords { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? FinishedAt { get; set; }

    public virtual ExternalSource Source { get; set; }
}