// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class TopicsLuanNtk
{
    public int TopicIdLuanNtk { get; set; }

    public string TopicName { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<TrendRecord> TrendRecords { get; set; } = new List<TrendRecord>();

    public virtual ICollection<UserFollowTopic> UserFollowTopics { get; set; } = new List<UserFollowTopic>();

    public virtual ICollection<KeywordsLuanNtk> Keywords { get; set; } = new List<KeywordsLuanNtk>();
}