// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class UsersHuyDd
{
    public int UserIdHuyDd { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string PhoneNumber { get; set; }

    public string AvatarUrl { get; set; }

    public string Organization { get; set; }

    public string AcademicTitle { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual ICollection<Bookmark> Bookmarks { get; set; } = new List<Bookmark>();

    public virtual ICollection<ImportedFile> ImportedFiles { get; set; } = new List<ImportedFile>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<PapersBaoTg> PapersBaoTgs { get; set; } = new List<PapersBaoTg>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<UserFollowJournal> UserFollowJournals { get; set; } = new List<UserFollowJournal>();

    public virtual ICollection<UserFollowKeyword> UserFollowKeywords { get; set; } = new List<UserFollowKeyword>();

    public virtual ICollection<UserFollowTopic> UserFollowTopics { get; set; } = new List<UserFollowTopic>();

    public virtual ICollection<RolesHuyDd> RoleIdHuyDds { get; set; } = new List<RolesHuyDd>();
}