// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScientificJournal.Entities.MinhPV.Models;

public partial class UserFollowTopic
{
    public int UserIdHuyDd { get; set; }

    public int TopicId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual TopicsLuanNtk Topic { get; set; }

    public virtual UsersHuyDd UserIdHuyDdNavigation { get; set; }
}